// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductGalleryWeather.API.Data;

#nullable disable

namespace ProductGalleryWeather.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductGalleryWeather.API.Models.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SrcUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GalleryImages");
                });

            modelBuilder.Entity("ProductGalleryWeather.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Doe",
                            ImageUrl = "/products/images/astro-fiction.png",
                            Price = 19.99m,
                            Title = "Astro Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Mary Poppins",
                            ImageUrl = "/products/images/black-dog.png",
                            Price = 20m,
                            Title = "Black Dog"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.D. Salinger",
                            ImageUrl = "/products/images/doomed-city.png",
                            Price = 16.99m,
                            Title = "Doomed City"
                        },
                        new
                        {
                            Id = 4,
                            Author = "F. Scott Fitzgerald",
                            ImageUrl = "/products/images/garden-girl.png",
                            Price = 14.99m,
                            Title = "Garden Girl"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Jane Austen",
                            ImageUrl = "/products/images/my-little-robot.png",
                            Price = 13.99m,
                            Title = "My little Robot"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Harper Lee",
                            ImageUrl = "/products/images/space-odissey.png",
                            Price = 11.99m,
                            Title = "SpaceOdissey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
